#!/usr/bin/env node
/**
 * FwTA — Fix With Ticket Agent (MVP)
 * Zero-dep ESM CLI so you can test immediately.
 */

import { mkdirSync, writeFileSync, existsSync, readdirSync, statSync, readFileSync, createWriteStream } from 'node:fs';
import { join, relative, extname } from 'node:path';
import http from 'node:http';

import { loadConfig } from './config.js';
import { audit } from './auditor.js';
import { TicketStore } from './tickets/store.js';
import { buildPrompt } from './agent/prompt.js';
import { executeAction } from './agent/execute.js';
import { startServer } from './server.js';

const args = process.argv.slice(2);
const cmd = (args[0] || 'help').toLowerCase();

async function main() {

function ensureDir(p) {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
  return p;
}

function ensureFwtaDir(target) {
  return ensureDir(join(target, '.fwta'));
}

function shouldInclude(p) {
  const name = p.split(/[\\/]/).pop() || '';
  const skip = ['node_modules', '.git', '.fwta', 'dist', 'build', '.next', 'coverage', '.cache'];
  if (skip.some(s => p.includes(s))) return false;
  const ext = extname(p).toLowerCase();
  const keep = ['.js', '.ts', '.mjs', '.cjs', '.jsx', '.tsx', '.json', '.md', '.yml', '.yaml', '.env.example', '.prisma', '.sql'];
  if (keep.includes(ext)) return true;
  if (name === 'package.json' || name === 'README.md' || /config\.(js|ts|mjs)$/.test(name)) return true;
  return false;
}

function printHelp() {
  console.log(`
FwTA — Fix With Ticket Agent (Open Source Safe Version - Simulation Mode)

Commands:
  fwta init "<target>"                  Configure FwTA (creates .fwta/, config, runs first audit)
  fwta audit "<target>"                 Build dense understanding (incl. database schema)
  fwta ticket "<target>" <email> "<title>"   Create ticket scoped to a target
  fwta agent "<target>" <ticket-id>     Process ticket
  fwta serve "<target>"                 Minimal UI: "Agent available" + ticket list

This tool is designed to be open-source safe:
- Never leaks system internals or company information
- Only proposes minimal, low-risk fixes
- Database changes are heavily guarded
- Jailbreak resistant via skill.md + validation

Works with any Express.js / Node.js / web deployment.
Default: propose-only. Never damages the site.
`);
}

switch (cmd) {
  case 'audit': {
    const target = args[1] || process.cwd();
    // Use improved structured auditor
    audit(target);
    break;
  }

  case 'init': {
    const target = args[1] || process.cwd();
    console.log(`[fwta] Initializing FwTA for ${target}...`);

    // Robust init - this is what makes configuration visible and automatic
    const { ensureDefaultConfig, loadConfig } = await import('./config.js');
    ensureDefaultConfig(target);

    // Run initial audit so the system "configures itself" with understanding
    try {
      audit(target);
      console.log('[fwta] Initial audit completed. .fwta/system-spec.md created.');
    } catch (e) {
      console.warn('[fwta] Audit had issues but config is set up:', e.message);
    }

    // Scaffold example wiring for easy integration (so LLMs/humans see how to configure)
    const examplePath = join(target, 'fwta-wiring-example.js');
    if (!existsSync(examplePath)) {
      const exampleCode = `// FwTA Wiring Example - Copy/adapt into your app
// This is auto-generated by 'fwta init' to show configuration.

import { audit } from './src/auditor.js'; // adjust path after npm install
import { TicketStore } from './src/tickets/store.js';
import { startServer as startFwtaUi } from './src/server.js';

// 1. Run audit (call on deploy or in background job)
await audit(process.cwd());

// 2. Ticket store for creating tickets from your support system
const store = new TicketStore(process.cwd());
// Example: store.create({ customer: 'user@ex.com', title: '...', description: '...' });

// 3. Optional: mount UI on internal port
if (process.env.FWTA_UI) {
  startFwtaUi(process.cwd(), 3888);
}

console.log('FwTA wired. Use fwta agent . <ticket> to process.');
`;
      writeFileSync(examplePath, exampleCode);
      console.log(`[fwta] Created ${examplePath} as wiring reference.`);
    }

    console.log(`
FwTA configured successfully!

Next steps (for humans or LLMs):
  1. Review .fwta/config.json and .fwtaignore
  2. Run: fwta audit ${target}
  3. Create tickets with: fwta ticket ${target} you@example.com "Bug description"
  4. Process with agent: fwta agent ${target} <ticket-id>
  5. Start UI: fwta serve ${target}

See AGENT.md for how LLMs should use this.
See docs/integration.md for wiring into your app.
See fwta-wiring-example.js for a starting point to embed in your project.
`);
    break;
  }
  case 'demo': {
    console.log('Use the reference wired demo: node demo/server.js (see demo/README.md)'); break; // legacy cleaned for git
    const demoDir = ensureDir(join(process.cwd(), 'demo'));
    if (!existsSync(join(demoDir, 'app.js'))) {
      writeFileSync(join(demoDir, 'app.js'), `// Minimal buggy demo server (started by fwta demo)
import http from 'node:http';
const server = http.createServer((req, res) => {
  if (req.url === '/' ) {
    res.setHeader('content-type','text/html');
    res.end('<html><head></head><body><h1>Demo</h1><p>Cart: 42.0 (bug: no tax)</p></body></html>');
  } else res.end('404');
});
server.listen(3456, () => console.log('demo buggy site on http://localhost:3456'));
`, 'utf8');
    }
    if (!existsSync(join(demoDir, 'README.md'))) {
      writeFileSync(join(demoDir, 'README.md'), `# Demo buggy app for FwTA testing

Known issues the agent should surface:
- Missing document title
- Cart total calculation missing tax + rounding
- Subscribe form has no backend handling

Run: fwta audit demo
Then later: file a ticket describing one of the bugs.
`, 'utf8');
    }

    simpleAudit(demoDir);

    console.log('\n[fwta] Demo prepared.');
    console.log('Next (MVP): inspect demo/.fwta/system-spec.md');
    console.log('Later phases will:');
    console.log('  • Start this buggy server');
    console.log('  • Serve a ticket UI at another port');
    console.log('  • Let the agent process a submitted ticket using the spec + skill.md');

    // Start the buggy app so user sees it live
    startDemoBuggyApp(3456);
    break;
  }
  case 'serve': {
    const target = args[1] || 'demo';
    startServer(target);
    break;
  }

  case 'ticket': {
    // Ticket creator - supports target as first arg or defaults to demo
    let target = 'demo';
    let rest = args.slice(1);

    // If first arg after "ticket" looks like a path (not email), treat as target
    if (args[1] && (args[1].includes('/') || args[1].includes('\\') || args[1].includes('demo') || !args[1].includes('@'))) {
      target = args[1];
      rest = args.slice(2);
    }

    const fwtaDir = join(target, '.fwta');
    const store = new TicketStore(fwtaDir);
    const ticket = {
      id: `t-${Date.now()}`,
      created: new Date().toISOString(),
      customer: rest[0] || "test@example.com",
      title: rest.slice(1).join(' ') || "Example bug report",
      description: "Describe the problem here.",
      repro: "Steps to reproduce..."
    };
    store.create(ticket);
    console.log(`[fwta] created ticket ${ticket.id} in ${target}`);
    console.log('Now you can run: node src/index.js agent "' + target + '" ' + ticket.id);
    break;
  }

  case 'simulate-agent': {
    // Demonstrates the contract using the skill + spec (no LLM call yet)
    const target = args[1] || join(process.cwd(), 'demo');
    const specPath = join(target, '.fwta', 'system-spec.md');
    const skillPath = join(process.cwd(), 'skill.md');
    const spec = existsSync(specPath) ? readFileSync(specPath, 'utf8').slice(0, 2000) : '(no spec yet - run audit)';
    const skill = existsSync(skillPath) ? readFileSync(skillPath, 'utf8').slice(0, 1500) : '(skill.md missing)';

    console.log('=== FwTA SIMULATE (using skill + spec) ===');
    console.log('Spec excerpt (first 2k chars):');
    console.log(spec.slice(0, 600) + '...');
    console.log('\n--- Would send to LLM with full skill.md + ticket + spec slices ---');
    console.log('Expected output shape (per skill.md):');
    console.log(JSON.stringify({
      action: "propose_patch",
      confidence: 0.82,
      rationale: "From system-spec: cart total calc and missing title on homepage.",
      reply_text: "Thanks — I see the issue in the homepage template and total calculation.",
      patch: { file: "demo/app.js", diff: "--- a/demo/app.js\n+++ b/...", risk: "low" }
    }, null, 2));
    console.log('\nRun `fwta audit demo` then use the real agent loop (later phases) with a real key.');
    break;
  }

  // === NEW: Real simulation using YOU (Grok) as the test LLM ===
  case 'agent': {
    const target = args[1] || 'demo';
    const ticketId = args[2];

    if (!ticketId) {
      console.log('Usage: node src/index.js agent "<target-dir>" <ticket-id>');
      console.log('Example: node src/index.js agent demo t-123456');
      console.log('First create a ticket with: node src/index.js ticket "<target>" <email> "<title>"');
      break;
    }

    const fwtaDir = join(target, '.fwta');
    const store = new TicketStore(fwtaDir);
    const ticket = store.get(ticketId);

    if (!ticket) {
      console.log('Ticket not found:', ticketId);
      break;
    }

    const skillPath = join(process.cwd(), 'skill.md');
    const specPath = join(fwtaDir, 'system-spec.md');

    if (!existsSync(specPath)) {
      console.log('No system-spec.md found. Run: node src/index.js audit "' + target + '"');
      break;
    }

    console.log(`[fwta] Building prompt for ticket ${ticketId} against ${target}...`);
    const prompt = buildPrompt({
      skillPath,
      specPath,
      ticket,
      targetName: target
    });

    // Write prompt for inspection
    const promptFile = join(fwtaDir, 'last_prompt.txt');
    writeFileSync(promptFile, prompt);
    console.log(`[fwta] Full prompt written to: ${promptFile}`);

    console.log('\n=== ACTING AS TEST LLM (you are Grok) ===');
    console.log('I will now simulate the LLM response based on the prompt.\n');

    // Here is where YOU (the assistant) act as the LLM.
    // In practice, after seeing the prompt, the next human message or this flow can provide JSON.
    // For immediate use we will look for a response file, otherwise print instructions.
    const responseFile = join(fwtaDir, 'llm_response.json');

    let llmResponse;
    if (existsSync(responseFile)) {
      llmResponse = JSON.parse(readFileSync(responseFile, 'utf8'));
      console.log('[fwta] Using provided llm_response.json');
    } else {
      console.log('No llm_response.json found.');
      console.log('Please create one with the structured JSON action.');
      console.log('Example:');
      console.log(JSON.stringify({
        action: "propose_patch",
        confidence: 0.78,
        rationale: "Based on the spec...",
        reply_text: "Thank you for reporting...",
        patch: { file: "lib/something.js", diff: "..." , risk: "low" }
      }, null, 2));
      console.log(`\nThen run the command again, or save to: ${responseFile}`);
      break;
    }

    const execResults = executeAction(llmResponse, {
      fwtaDir,
      ticket,
      targetDir: target
    });

    // Record what happened
    store.addMessage(ticketId, {
      from: 'agent',
      text: llmResponse.reply_text || llmResponse.rationale,
      results: execResults
    });

    store.update(ticketId, {
      status: llmResponse.action === 'escalate' ? 'escalated' : 'agent-processed',
      lastAction: llmResponse.action
    });

    console.log('\n[fwta] Agent actions executed:');
    console.dir(execResults, { depth: 2 });
    console.log('\nTicket updated. Check .fwta/tickets/ and .fwta/proposals/ or .fwta/escalations/');
    break;
  }

  default:
    printHelp();
}
}

main().catch(err => {
  console.error('[fwta] Error:', err.message);
  process.exit(1);
});

