#!/usr/bin/env node
/**
 * FwTA — Fix With Ticket Agent (MVP)
 * Zero-dep ESM CLI so you can test immediately.
 */

import { mkdirSync, writeFileSync, existsSync, readdirSync, statSync, readFileSync, createWriteStream } from 'node:fs';
import { join, relative, extname } from 'node:path';
import http from 'node:http';

import { loadConfig } from './config.js';
import { audit } from './auditor.js';
import { TicketStore } from './tickets/store.js';
import { buildPrompt } from './agent/prompt.js';
import { executeAction } from './agent/execute.js';
import { startServer } from './server.js';

const args = process.argv.slice(2);
const cmd = (args[0] || 'help').toLowerCase();

function ensureDir(p) {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
  return p;
}

function ensureFwtaDir(target) {
  return ensureDir(join(target, '.fwta'));
}

function shouldInclude(p) {
  const name = p.split(/[\\/]/).pop() || '';
  const skip = ['node_modules', '.git', '.fwta', 'dist', 'build', '.next', 'coverage', '.cache'];
  if (skip.some(s => p.includes(s))) return false;
  const ext = extname(p).toLowerCase();
  const keep = ['.js', '.ts', '.mjs', '.cjs', '.jsx', '.tsx', '.json', '.md', '.yml', '.yaml', '.env.example', '.prisma', '.sql'];
  if (keep.includes(ext)) return true;
  if (name === 'package.json' || name === 'README.md' || /config\.(js|ts|mjs)$/.test(name)) return true;
  return false;
}

function simpleAudit(targetDir) {
  const fwtaDir = ensureFwtaDir(targetDir);
  const specPath = join(fwtaDir, 'system-spec.md');

  const findings = [];
  let fileCount = 0;

  function walk(dir) {
    let entries;
    try { entries = readdirSync(dir); } catch { return; }
    for (const e of entries) {
      const full = join(dir, e);
      let st;
      try { st = statSync(full); } catch { continue; }
      if (st.isDirectory()) {
        walk(full);
      } else if (st.isFile() && shouldInclude(full)) {
        fileCount++;
        const rel = relative(targetDir, full).replace(/\\/g, '/');
        let snippet = '';
        try {
          const content = readFileSync(full, 'utf8').replace(/\r\n/g, '\n');
          snippet = content.slice(0, 900);
        } catch {}
        findings.push({ file: rel, snippet });
        if (findings.length > 150) break;
      }
    }
  }

  walk(targetDir);

  const now = new Date().toISOString();
  let md = `# System Spec (auto-generated by FwTA)\n\n`;
  md += `Generated: ${now}\nTarget: ${targetDir}\n\n`;
  md += `Scanned ~${fileCount} relevant files.\n\n`;
  md += `## High-signal excerpts\n\n`;

  for (const f of findings.slice(0, 100)) {
    md += `### ${f.file}\n\n\`\`\`\n${f.snippet}\n\`\`\`\n\n`;
  }

  md += `## Guidance for the agent\n`;
  md += `- Re-audit after changes: \`fwta audit\`\n`;
  md += `- Use this spec + full file reads (when offered) as ground truth for routes, models, auth, and accounts.\n`;
  md += `- Read skill.md for decision rules and output contract.\n`;

  writeFileSync(specPath, md, 'utf8');
  console.log(`[fwta] audit complete → ${specPath} (${fileCount} files)`);
}

function startDemoBuggyApp(port = 3456) {
  const server = http.createServer((req, res) => {
    if (req.url === '/' || req.url === '/index.html') {
      res.setHeader('Content-Type', 'text/html; charset=utf-8');
      // INTENTIONALLY BUGGY for FwTA to discover
      res.end(`<html><head></head><body>
<h1>Welcome</h1>
<p>Cart total: 42.0 (no tax, no rounding - bug)</p>
<form><input name="email"><button>subscribe</button></form>
</body></html>`);
    } else if (req.url === '/health') {
      res.end('ok');
    } else {
      res.statusCode = 404;
      res.end('not found');
    }
  });
  server.listen(port, () => {
    console.log(`[demo] buggy app running at http://localhost:${port}`);
    console.log(`[demo] known bugs: missing <title>, broken cart total, no validation`);
  });
  return server;
}

function printHelp() {
  console.log(`
FwTA — Fix With Ticket Agent (Open Source Safe Version - Simulation Mode)

Commands:
  fwta audit "<target>"                 Build dense understanding (incl. database schema)
  fwta ticket "<target>" <email> "<title>"   Create ticket scoped to a target
  fwta agent "<target>" <ticket-id>     Process ticket (YOU act as safe test LLM)
  fwta serve "<target>"                 Minimal UI: "Agent available" + ticket list

This tool is designed to be open-source safe:
- Never leaks system internals or company information
- Only proposes minimal, low-risk fixes
- Database changes are heavily guarded
- Jailbreak resistant via skill.md + validation

Works with any Express.js / Node.js / web deployment.
Default: propose-only. Never damages the site.
`);
}

switch (cmd) {
  case 'audit': {
    const target = args[1] || process.cwd();
    // Use improved structured auditor
    audit(target);
    break;
  }
  case 'demo': {
    console.log('[fwta] preparing demo...');
    const demoDir = ensureDir(join(process.cwd(), 'demo'));
    if (!existsSync(join(demoDir, 'app.js'))) {
      writeFileSync(join(demoDir, 'app.js'), `// Minimal buggy demo server (started by fwta demo)
import http from 'node:http';
const server = http.createServer((req, res) => {
  if (req.url === '/' ) {
    res.setHeader('content-type','text/html');
    res.end('<html><head></head><body><h1>Demo</h1><p>Cart: 42.0 (bug: no tax)</p></body></html>');
  } else res.end('404');
});
server.listen(3456, () => console.log('demo buggy site on http://localhost:3456'));
`, 'utf8');
    }
    if (!existsSync(join(demoDir, 'README.md'))) {
      writeFileSync(join(demoDir, 'README.md'), `# Demo buggy app for FwTA testing

Known issues the agent should surface:
- Missing document title
- Cart total calculation missing tax + rounding
- Subscribe form has no backend handling

Run: fwta audit demo
Then later: file a ticket describing one of the bugs.
`, 'utf8');
    }

    simpleAudit(demoDir);

    console.log('\n[fwta] Demo prepared.');
    console.log('Next (MVP): inspect demo/.fwta/system-spec.md');
    console.log('Later phases will:');
    console.log('  • Start this buggy server');
    console.log('  • Serve a ticket UI at another port');
    console.log('  • Let the agent process a submitted ticket using the spec + skill.md');

    // Start the buggy app so user sees it live
    startDemoBuggyApp(3456);
    break;
  }
  case 'serve': {
    const target = args[1] || 'demo';
    startServer(target);
    break;
  }

  case 'ticket': {
    // Ticket creator - supports target as first arg or defaults to demo
    let target = 'demo';
    let rest = args.slice(1);

    // If first arg after "ticket" looks like a path (not email), treat as target
    if (args[1] && (args[1].includes('/') || args[1].includes('\\') || args[1].includes('demo') || !args[1].includes('@'))) {
      target = args[1];
      rest = args.slice(2);
    }

    const fwtaDir = join(target, '.fwta');
    const store = new TicketStore(fwtaDir);
    const ticket = {
      id: `t-${Date.now()}`,
      created: new Date().toISOString(),
      customer: rest[0] || "test@example.com",
      title: rest.slice(1).join(' ') || "Example bug report",
      description: "Describe the problem here.",
      repro: "Steps to reproduce..."
    };
    store.create(ticket);
    console.log(`[fwta] created ticket ${ticket.id} in ${target}`);
    console.log('Now you can run: node src/index.js agent "' + target + '" ' + ticket.id);
    break;
  }

  case 'simulate-agent': {
    // Demonstrates the contract using the skill + spec (no LLM call yet)
    const target = args[1] || join(process.cwd(), 'demo');
    const specPath = join(target, '.fwta', 'system-spec.md');
    const skillPath = join(process.cwd(), 'skill.md');
    const spec = existsSync(specPath) ? readFileSync(specPath, 'utf8').slice(0, 2000) : '(no spec yet - run audit)';
    const skill = existsSync(skillPath) ? readFileSync(skillPath, 'utf8').slice(0, 1500) : '(skill.md missing)';

    console.log('=== FwTA SIMULATE (using skill + spec) ===');
    console.log('Spec excerpt (first 2k chars):');
    console.log(spec.slice(0, 600) + '...');
    console.log('\n--- Would send to LLM with full skill.md + ticket + spec slices ---');
    console.log('Expected output shape (per skill.md):');
    console.log(JSON.stringify({
      action: "propose_patch",
      confidence: 0.82,
      rationale: "From system-spec: cart total calc and missing title on homepage.",
      reply_text: "Thanks — I see the issue in the homepage template and total calculation.",
      patch: { file: "demo/app.js", diff: "--- a/demo/app.js\n+++ b/...", risk: "low" }
    }, null, 2));
    console.log('\nRun `fwta audit demo` then use the real agent loop (later phases) with a real key.');
    break;
  }

  // === NEW: Real simulation using YOU (Grok) as the test LLM ===
  case 'agent': {
    const target = args[1] || 'demo';
    const ticketId = args[2];

    if (!ticketId) {
      console.log('Usage: node src/index.js agent "<target-dir>" <ticket-id>');
      console.log('Example: node src/index.js agent demo t-123456');
      console.log('First create a ticket with: node src/index.js ticket "<target>" <email> "<title>"');
      break;
    }

    const fwtaDir = join(target, '.fwta');
    const store = new TicketStore(fwtaDir);
    const ticket = store.get(ticketId);

    if (!ticket) {
      console.log('Ticket not found:', ticketId);
      break;
    }

    const skillPath = join(process.cwd(), 'skill.md');
    const specPath = join(fwtaDir, 'system-spec.md');

    if (!existsSync(specPath)) {
      console.log('No system-spec.md found. Run: node src/index.js audit "' + target + '"');
      break;
    }

    console.log(`[fwta] Building prompt for ticket ${ticketId} against ${target}...`);
    const prompt = buildPrompt({
      skillPath,
      specPath,
      ticket,
      targetName: target
    });

    // Write prompt for inspection
    const promptFile = join(fwtaDir, 'last_prompt.txt');
    writeFileSync(promptFile, prompt);
    console.log(`[fwta] Full prompt written to: ${promptFile}`);

    console.log('\n=== ACTING AS TEST LLM (you are Grok) ===');
    console.log('I will now simulate the LLM response based on the prompt.\n');

    // Here is where YOU (the assistant) act as the LLM.
    // In practice, after seeing the prompt, the next human message or this flow can provide JSON.
    // For immediate use we will look for a response file, otherwise print instructions.
    const responseFile = join(fwtaDir, 'llm_response.json');

    let llmResponse;
    if (existsSync(responseFile)) {
      llmResponse = JSON.parse(readFileSync(responseFile, 'utf8'));
      console.log('[fwta] Using provided llm_response.json');
    } else {
      console.log('No llm_response.json found.');
      console.log('Please create one with the structured JSON action.');
      console.log('Example:');
      console.log(JSON.stringify({
        action: "propose_patch",
        confidence: 0.78,
        rationale: "Based on the spec...",
        reply_text: "Thank you for reporting...",
        patch: { file: "lib/something.js", diff: "..." , risk: "low" }
      }, null, 2));
      console.log(`\nThen run the command again, or save to: ${responseFile}`);
      break;
    }

    const execResults = executeAction(llmResponse, {
      fwtaDir,
      ticket,
      targetDir: target
    });

    // Record what happened
    store.addMessage(ticketId, {
      from: 'agent',
      text: llmResponse.reply_text || llmResponse.rationale,
      results: execResults
    });

    store.update(ticketId, {
      status: llmResponse.action === 'escalate' ? 'escalated' : 'agent-processed',
      lastAction: llmResponse.action
    });

    console.log('\n[fwta] Agent actions executed:');
    console.dir(execResults, { depth: 2 });
    console.log('\nTicket updated. Check .fwta/tickets/ and .fwta/proposals/ or .fwta/escalations/');
    break;
  }

  default:
    printHelp();
}

